### ISSUE TITLE
foundToken error

### ISSUE THREAD

**Issue by broganciaran** [BytePhoenixData/BSCTokenSniper#35]
**Description:** Error is triggered when trying to monitor a token to autosell when it is already monitoring another token to sell.

**Error:**
[16:08:53.676] [Token] New potential token detected: ThankYouElon (thankyouelon.fun): 0x843E7471B8AF7Cce4f37D7A9Bf465bBB70B43CA6
[16:08:54.507] [Token] Liquidity amount: 0.25BNB
[16:08:54.513] [Token] Starting Mini Audit...
[16:08:55.587] [Token] RugDoc Pass
[16:08:55.593] [SUCCESS] Token has passed mini audit.
[16:08:57.355] [BUY] Successfully bought $thankyouelon.fun for 0.0019 BNB - TX ID:  0xe61b7c548140a68354671730a19dedcd35cd6e8b7d4ffc4fe21888ac0a7e26c0
[16:08:57.627] [SELL] Monitoring $thankyouelon.fun and selling at 2.01x original price.
**[ERROR] foundToken error, please notify dev:**
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "BSCTokenSniper.py", line 281, in monitor_and_sell
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\contract.py", line 957, in call
    return call_contract_function(
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 147, in _make_request
    return request_func(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 546, in foundToken
  File "BSCTokenSniper.py", line 240, in approve_token_for_sell
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\contract.py", line 957, in call
    return call_contract_function(
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 147, in _make_request
    return request_func(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\gas_price_strategy.py", line 84, in middleware
    return make_request(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\providers\websocket.py", line 144, in make_request
    return future.result()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\providers\websocket.py", line 130, in coro_make_request
    await asyncio.wait_for(
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\protocol.py", line 385, in recv
    raise RuntimeError(
RuntimeError: cannot call recv while another coroutine is already waiting for the next message

response = make_request(method, params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\gas_price_strategy.py", line 84, in middleware
    return make_request(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\providers\websocket.py", line 144, in make_request
    return future.result()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\providers\websocket.py", line 125, in coro_make_request
    await asyncio.wait_for(
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\protocol.py", line 471, in send
    await self.ensure_open()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\protocol.py", line 735, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), no reason

**Comment by meanstackofdoom** [comment]
I can confirm I am also getting this error.

**Comment by YetAnotherAccountCreated** [comment]
Also received today:
[09:43:49.212] [Token] New potential token detected: Lucifer NFT (LCF): 0x66aF9D082667d3c2CFb9271c155e63e933288e44
[09:43:50.316] [Token] Liquidity amount: 1.5114BNB
[09:43:50.332] [Token] Starting Mini Audit...
[09:43:52.539] [Token] RugDoc Pass
[09:43:52.556] [SUCCESS] Token has passed mini audit.
[09:43:56.015] [BUY] Successfully bought $LCF for 0.002 BNB - TX ID:  0xfd5af57d8a5bef6a2c4f305c50f9d8b9edd0ed2f8d226570722097fcb0f00880
[09:43:56.538] [SELL] Monitoring $LCF and selling at 2.0x original price.
[ERROR] foundToken error, please notify dev:
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 546, in foundToken
  File "BSCTokenSniper.py", line 240, in approve_token_for_sell
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\contract.py", line 957, in call
    return call_contract_function(
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\manager.py", line 147, in _make_request
    return request_func(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\middleware\gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\middleware\attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\middleware\buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\providers\websocket.py", line 144, in make_request
    return future.result()
  File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\web3\providers\websocket.py", line 130, in coro_make_request
    await asyncio.wait_for(
  File "C:\Program Files\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python39\site-packages\websockets\legacy\protocol.py", line 385, in recv
    raise RuntimeError(
RuntimeError: cannot call recv while another coroutine is already waiting for the next message
