### ISSUE TITLE
ERROR - Buytoken error, please notify dev

### ISSUE THREAD

**Issue by CryptoCarlos21** [BytePhoenixData/BSCTokenSniper#36]
**Version 1.3**
**OS: Windows**
**Python Version 3.9**
**Sample token with error** : EmpireDEX (EMPIRE): 0xc83859C413a6bA5ca1620cD876c7E33a232c1C34

Every token that passes the mini audit is failing with this error:

```
[ERROR] buyToken error, please notify dev:
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 353, in Buy
TypeError: can only concatenate str (not "float") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BSCTokenSniper.py", line 359, in Buy
TypeError: can only concatenate str (not "TypeError") to str
```

**Config settings** (excluded personal settings such as API / Wallet address etc

```
 "amountToSpendPerSnipe": "0.00025",
   "transactionRevertTimeSeconds": "10000",
   "gasAmount": "250000",
   "gasPrice": "5",
   "liquidityPairAddress": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
   "antiBotDelay": "10",
   "minLiquidityAmount": "0.1",
   "autoSell": "True",
   "autoSellTakeProfitMultiplier": "1.51",
   "approveSellTimeDelay": "10",
   "observeOnly": "False",
   "checkSourceCode": "True",
   "checkHoneypot": "True",
   "checkForTest": "True"

```

**Comment by compunerd4** [comment]
**Update**
My antibotdelay value was modifed from the default 0 to 10. This may have been the cause. 
I reset it back to 0 and stopped receiving this error

**Comment by BytePhoenixData** [comment]
v1.4 fixes that, u can access it in telegram theres a link for bsctokensniper testing
