### ISSUE TITLE
ERROR - tokenLoop error, please notify dev

### ISSUE THREAD

**Issue by YetAnotherAccountCreated** [BytePhoenixData/BSCTokenSniper#38]
I let v1.3 run through the night. No issues before I went to bed, but I woke up to this error:
[ERROR] tokenLoop error, please notify dev:
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 596, in tokenLoop
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python39\site-packages\web3\_utils\filters.py", line 160, in get_new_entries
    log_entries = self._filter_valid_entries(self.eth_module.get_filter_changes(self.filter_id))
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python39\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python39\site-packages\web3\manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python39\site-packages\web3\manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'filter not found'}

 My adjusted settings were:
   "amountToSpendPerSnipe": "0.002",
   "minLiquidityAmount": "1",
   "autoSellTakeProfitMultiplier": "2",
   "approveSellTimeDelay": "15",

**Comment by Manuu1987** [comment]
I am having this error also. Was you able to overcome?

**Comment by NKVDL** [comment]
I can not edit the source code as it is encrypted, but the error has to do with asynchronous filter handling, and my best guess it has something to do with querying the websocket events in web3. 

https://web3py.readthedocs.io/en/stable/v4_migration.html?highlight=%27filter%20not%20found%27#filters 

I have the same error.

**Comment by BytePhoenixData** [comment]
v1.4 fixes that, u can access it in telegram theres a link for bsctokensniper testing
