### ISSUE TITLE
Error at selling stage

### ISSUE THREAD

**Issue by Himbron** [BytePhoenixData/BSCTokenSniper#50]
This error occurs after buying the token and then trying to approve the token for selling

[16:15:19.470] [SELL] Monitoring $xpnet and selling at 3.0x original price.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
[ERROR] foundToken error, please notify dev:
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "BSCTokenSniper.py", line 282, in monitor_and_sell
IndexError: list index out of range
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 546, in foundToken
  File "BSCTokenSniper.py", line 241, in approve_token_for_sell
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\contract.py", line 957, in call
    return call_contract_function(
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 147, in _make_request
    return request_func(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\middleware\buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\providers\websocket.py", line 144, in make_request
    return future.result()
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\providers\websocket.py", line 130, in coro_make_request
    await asyncio.wait_for(
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\protocol.py", line 385, in recv
    raise RuntimeError(
RuntimeError: cannot call recv while another coroutine is already waiting for the next message

**Comment by maverik7719** [comment]
also for me here

**Comment by tuttowp** [comment]
> also for me here

Ask here that is the real developer of the code they are using https://github.com/CodeWithJoe2020/pythonSniperbot/blob/main/sniper.py

**Comment by BytePhoenixData** [comment]
v1.4 has fixed that, please see telegram link to join testing group to get access to v1.4 beta
