### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lokespas** [BytePhoenixData/BSCTokenSniper#57]
Hi 

I get this issure when im running the bot 

[ERROR] Please notify dev:
Traceback (most recent call last):
  File "C:\Users\Bruger\python\BSCTokenSniper.py", line 191, in Buy
    tx_token = web3.eth.send_raw_transaction(signed_txn.rawTransaction) #BUY THE TOKEN
  File "C:\Users\Bruger\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\Bruger\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\web3\manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "C:\Users\Bruger\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\web3\manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'nonce too low'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Bruger\python\BSCTokenSniper.py", line 193, in Buy
    print(style.RED + currentTimeStamp + " Transaction failed: " + ex)
TypeError: can only concatenate str (not "ValueError") to str

**Comment by BytePhoenixData** [comment]
Fixed in more recent version, v1.4 beta is available use that, link is in telegram gorup
