### ISSUE TITLE
buyToken error, please notify dev?

### ISSUE THREAD

**Issue by Kingphilly808** [BytePhoenixData/BSCTokenSniper#58]
Hey team love the work! the buy function is throwing this error:

[ERROR] buyToken error, please notify dev:
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 356, in Buy
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\eth_utils\decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\eth_account\account.py", line 727, in sign_transaction
    account = self.from_key(private_key)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\eth_utils\decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\eth_account\account.py", line 250, in from_key
    key = self._parsePrivateKey(private_key)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\eth_utils\decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\eth_account\account.py", line 774, in _parsePrivateKey
    return self._keys.PrivateKey(HexBytes(key))
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hexbytes\main.py", line 23, in __new__
    bytesval = to_bytes(val)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hexbytes\_utils.py", line 17, in to_bytes
    return hexstr_to_bytes(val)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hexbytes\_utils.py", line 50, in hexstr_to_bytes
    return binascii.unhexlify(ascii_hex)
binascii.Error: Non-hexadecimal digit found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BSCTokenSniper.py", line 359, in Buy
TypeError: can only concatenate str (not "Error") to str

**Comment by BytePhoenixData** [comment]
Looks to be a problem with your private key. Be aware though v1.3 and earlier is abandoned in favour of v1.4 beta, its on the telegram group's pinned messages
